export const PAGE = {
    HOME:'HOME',
    ABOUT:'ABOUT',
    RESUME:'RESUME',
    CONTACT:'CONTACT',
    BLOG:'BLOG',
    LITTLEGAMES:'LITTLEGAMES',
    DRUMGAME:"DRUMGAME",
    SIMONGAME:"SIMONGAME",

}